import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@components/Navbar";
import Footer from "@components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="w-full font-main bg-back1 text-primary ">
					<div className="min-h-screen">
						<Navbar />
						<div className="w-full pt-10 px-5 md:px-[5%] lg:px-[12%] ">
							{children}
						</div>
					</div>
					<Footer />
				</div>
			</body>
		</html>
	);
}
