import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@components/Navbar";
import Footer from "@components/Footer";
import SideBar from "@components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Navbar />
				<div className="w-full font-main bg-back1 text-primary flex  ">

					<div className="w-full lg:w-10/12 pt-10 px-5 md:px-[5%] lg:px-[8%] ">
						{children}
					</div>
					<div className="hidden lg:block w-2/12 h-[90vh] px-3 pt-10 ">
						<SideBar />
					</div>

				</div>
				<Footer />
			</body>
		</html >
	);
}
