import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@components/en/Navbar";
import Footer from "@components/en/Footer";
import SideBar from "@components/en/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="font-main">

					<Navbar />
					<div className="w-full  bg-back1 text-primary flex flex-row justify-center ">

						<div className="w-full lg:w-12/12 ">
							{children}
						</div>
						{/* <div className="hidden lg:block w-2/12 h-[90vh] px-3 pt-10 ">
							<SideBar />
						</div> */}

					</div>
					<Footer />
				</div>
			</body>
		</html >
	);
}
